defaults:
  - _self_
  - io: default
  - conformers: default
  - calculator: mace
  - optimiser@local_optimiser: bfgs
  - optimiser@global_optimiser: bfgs
  - experiment: null

seed: -1
threshold: 16.1
num_workers: 0
device: cpu
batch_size: -1

local_optimiser:
  fmax: 0.50
