seed: 10
threshold: 16.1
num_workers: 0
device: cpu
batch_size: 32

io:
  input:
    parquet_path: null
    mol_col_name: null
    id_col_name: null
    include_charged: true
  output:
    parquet_path: null
    mol_col_name: ${..input.mol_col_name}
    id_col_name: ${..input.id_col_name}

conformers:
  randomSeed: ${seed}
  numConfs: 20
  maxAttempts: 10
  pruneRmsThresh: 0.1
  clearConfs: false
  numThreads: ${num_workers}

calculator:
  _target_: neural_optimiser.calulator.MACECalculator
  model_paths: path
  device: ${device}
  default_dtype: float32
  # energy_units: eV

local_optimiser:
  _target_: neural_optimiser.optimiser.BFGS
  max_step: 0.04
  steps: 250
  fmax: 0.50
  fexit: null

global_optimiser:
  _target_: neural_optimiser.optimiser.BFGS
  max_step: 0.04
  steps: 250
  fmax: 0.05
  fexit: null

energy_evalulation:
  calculator:
    _target_: neural_optimiser.calulator.AnotherCalculator
    model_paths: path
    device: ${device}
    default_dtype: float32
